### ISSUE TITLE
Imperative examples could use some updating

### ISSUE THREAD

**Issue by spkane** [aws-samples/eks-gitops-crossplane-argocd#1]
* crossplane version: `v1.6.2`
* aws-provider: `v0.23.0`
* Provider can be easily installed with:
  * `kubectl crossplane install provider crossplane/provider-aws:v0.23.0`

* In the `composition.yaml`:
  * `kind: ElasicIP` should be replaced with `kind: Address`
  * and `apiVersion: ec2.aws.crossplane.io/v1alpha1` should be replaced with `apiVersion: ec2.aws.crossplane.io/v1beta1` 

* To get mine working, I also pointed
 `crossplane.yaml`
 at the upstream container image:

```yaml
  dependsOn:
    - provider: crossplane/provider-aws
      version: ">=v0.20.0"
```
